# Generated by Django 4.1.1 on 2022-09-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateur', '0002_attente_fini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fini',
            name='fait_par',
            field=models.CharField(max_length=200),
        ),
    ]
